// Game lists. To add a game, add a row here.
const O="https://www.onlinegames.io/games/",C="https://cloud.onlinegames.io/games/",IMG="https://www.onlinegames.io/media/posts/";
const R="/responsive/";
// [title, "o:"|"c:" + embed path, thumbnail path, category]. Full feed: https://www.onlinegames.io/media/plugins/genGames/embed.json
const DATA=[
["Steal Brainrots Multiplayer","c:2026/unity/steal-brainrots-multiplayer/game.html","1340"+R+"steal-brainrots-multiplayer-2-xs.webp","Sim"],
["Drift King","o:2024/unity/drift-king/index.html","729"+R+"Drift-King-xs.jpg","Racing"],
["Stack Fire Ball","o:2021/unity/stack-fire-ball/index.html","184"+R+"Stack-Fire-Ball-Game-xs.jpg","Arcade"],
["Geometry Dash FreezeNova","o:2023/q2/geometry-dash-freezenova/index.html","510"+R+"Geometry-Dash-FreezeNova-xs.jpg","Arcade"],
["Dinosaur Game","o:2023/q2/dinosaur-game/index.html","417"+R+"Dinosaur-Game-Online-xs.jpg","Arcade"],
["Marble Run","c:2026/galatrix/marble-run/game.html","1354"+R+"marble-run-xs.webp","Arcade"],
["Pinball Simulator","o:2021/unity2/pinball-simulator/index.html","460"+R+"Pinball-Simulator-xs.jpg","Arcade"],
["Snaker io","c:2026/more/snaker-io/game.html","1261"+R+"snaker-io-xs.webp","Arcade"],
["Stickman Parkour","c:2024/construct/219/stickman-parkour/index-og.html","871"+R+"stickman-parkour-OG-xs.jpg","Arcade"],
["Velocity Rush","c:2026/unity/velocity-rush/game.html","1265"+R+"velocity-rush-xs.webp","Arcade"],
["Stickman Destruction","o:2021/unity3/stickman-destruction/index.html","233"+R+"Stickman-Destruction-xs.jpg","Arcade"],
["Troll Level","c:2024/unity2/troll-level/index-og.html","857"+R+"troll-level-online-xs.jpg","Arcade"],
["Geometry Vector","c:2026/construct/329/geometry-vector/game.html","1246"+R+"geometry-vector-xs.webp","Arcade"],
["Geometry Escape","c:2024/construct/299/geometry-escape/index-og.html","905"+R+"Geometry-Escape-xs.jpg","Arcade"],
["Get On Top","o:2024/code/6/get-on-top/index.html","697"+R+"Get-on-Top-xs.jpg","2 Player"],
["Drunken Duel","o:2024/code/2/drunken-duel/index.html","698"+R+"Drunken-Duel-xs.jpg","2 Player"],
["Tank Arena","c:2025/construct/293/tank-arena/index-og.html","956"+R+"Tank-Arena-Online-xs.jpg","Arcade"],
["Dont Fall io","o:2021/unity/dont-fall-io/index.html","182"+R+"Dont-Fall-io-2-xs.jpg","Arcade"],
["Crazy Ball Adventures","o:2021/unity2/crazy-ball-adventures/index.html","760"+R+"Crazy-Ball-Game-xs.jpg","Arcade"],
["Backflip Challenge","c:2026/unity/backflip-challenge/game.html","1203"+R+"backflip-challenge-xs.webp","Arcade"],
["Kick The Dummy","o:2022/construct/153/kick-the-dummy/index.html","414"+R+"Kick-The-Dummy-Game-xs.jpg","Arcade"],
["Crazy Stickman Physics","o:2023/construct/185/crazy-stickman-physics/index.html","715"+R+"Crazy-Stickman-Physics-xs.jpg","Arcade"],
["Fall Brainrots","c:2026/unity/fall-brainrots/game.html","1194"+R+"fall-brainrots-xs.webp","Arcade"],
["Steal Brainrot Heist","c:2026/unity/steal-brainrot-heist/game.html","1180"+R+"steal-brainrot-heist-2-xs.webp","Arcade"],
["Shortcut Race","o:2023/construct/237/shortcut-race/index.html","492"+R+"Shortcut-Race-xs.jpg","Arcade"],
["Bus Subway Runner","o:2022/unity/bus-subway-runner/index.html","235"+R+"Bus-Subway-Runner-Game-xs.jpg","Arcade"],
["Snake Wars","o:2024/unity/snake-wars/index.html","638"+R+"Snake-Wars-Free-Game-xs.jpg","Arcade"],
["Trains io","o:2023/construct/235/trains-io/index.html","470"+R+"Trains-io-Game-xs.jpg","Arcade"],
["Dublix","c:2025/unity4/dublix/game-og.html","1126"+R+"dublix-xs.webp","Arcade"],
["Highway Traffic","o:2022/unity/highway-traffic/index.html","32"+R+"Highway-Traffic-2-xs.jpg","Racing"],
["Drift Hunters Pro","o:2023/unity/drift-hunters-pro/index.html","397"+R+"Drift-Hunters-Pro-xs.jpg","Racing"],
["Escape Car","c:2025/unity2/escape-car/index-og.html","1000"+R+"Escape-Car-xs.jpg","Racing"],
["Super Mini Racing","o:2022/unity4/super-mini-racing/index.html","819"+R+"Super-Mini-Racing-xs.jpg","Racing"],
["Ultimate Moto","c:2021/2/ultimate-moto/index-og.html","1020"+R+"ultimate-moto-xs.jpg","Racing"],
["Edys Car Simulator","o:2022/unity/edys-car-simulator/index.html","238"+R+"Edys-Car-Simulator-Online-xs.jpg","Racing"],
["Madalin Stunt Cars Pro","o:2023/unity/madalin-stunt-cars-pro/index.html","401"+R+"Madalin-Stunt-Cars-Pro-Game-xs.jpg","Racing"],
["Burnout City","c:2024/unity/burnout-city/index-og.html","861"+R+"burnoutcity-xs.jpg","Racing"],
["Crazy Drifter","o:2022/unity3/crazy-drifter/index.html","314"+R+"Crazy-Drifter-xs.jpg","Racing"],
["Highway Racer Pro","o:2024/unity/highway-racer-pro/index.html","822"+R+"Highway-Racer-Pro-xs.jpg","Racing"],
["Motorbike Stunt Simulator","c:2021/unity/motorbike-stunt-simulator/index-og.html","1045"+R+"motorbike_stunt_simulator_game-2-xs.webp","Racing"],
["Poly Racing Cars","c:2022/unity3/poly-racing-cars/index-og.html","835"+R+"Poly-racing-cars-image-xs.jpg","Racing"],
["Crazy Car Arena","o:2022/unity3/crazy-car-arena/index.html","317"+R+"Crazy-Car-Arena-Game-xs.jpg","Racing"],
["Stunt Rider","o:2024/unity/stunt-rider/index.html","674"+R+"Stunt-Rider-Online-xs.jpg","Racing"],
["Real Flight Simulator","c:2023/unity2/real-flight-simulator/index.html","342"+R+"Real-Flight-Simulator-2-xs.jpg","Racing"],
["Airplane Racer","o:2022/unity/airplane-racer/index.html","268"+R+"Airplane-Racer-xs.jpg","Racing"],
["Taxi Simulator","o:2022/unity/taxi-simulator/index.html","465"+R+"Taxi-Simulator-xs.jpg","Racing"],
["Jeep Racing","o:2023/freezenova.com/jeep-racing/index.html","564"+R+"Jeep-Racing-xs.jpg","Racing"],
["Powerslide Kart Simulator","o:2022/unity3/powerslide-kart-simulator/index.html","578"+R+"Powerslide-Kart-Simulator-xs.jpg","Racing"],
["Super Car Driving","c:2024/unity2/super-car-driving/index-og.html","854"+R+"supercardriving-2-xs.jpg","Racing"],
["Monster Truck City Parking","o:2021/unity/monster-truck-city-parking/index.html","582"+R+"Monster-Truck-City-Parking-xs.jpg","Racing"],
["Pixel Driver","c:2021/unity3/pixel-driver/index-og.html","990"+R+"Pixel-Driver-xs.jpg","Racing"],
["Egg Car Racing","c:2024/construct/289/egg-car-racing/index-og.html","910"+R+"egg-car-racing-xs.jpg","Racing"],
["2048","c:2025/html/2048/index.html","916"+R+"2048-xs.jpg","Puzzle"],
["Block Blast","c:2024/unity3/block-blast/index-og.html","876"+R+"block-blast-xs.jpg","Puzzle"],
["Mahjong","c:2025/unity/mahjong/index-og.html","966"+R+"Mahjong-xs.jpg","Puzzle"],
["Tile Match","c:2025/unity/tile-match/index-og.html","939"+R+"tile-match-xs.jpg","Puzzle"],
["Cake Match Puzzle","c:2024/unity3/cake-match-puzzle/index-og.html","908"+R+"55-xs.jpg","Puzzle"],
["Chess FreezeNova","c:2025/unity3/chess/index-og.html","1116"+R+"chess-freezenova-xs.webp","Puzzle"],
["Solitaire Adventure","o:2022/unity4/solitaire-adventure/index.html","519"+R+"Solitaire-Adventure-Tripeaks-xs.jpg","Puzzle"],
["Nuts and Bolts Puzzle","c:2025/unity/nuts-and-bolts-puzzle/index-og.html","965"+R+"nuts-and-bolts-puzzle-xs.jpg","Puzzle"],
["Four Colors","o:2023/code/four-colors/index.html","535"+R+"Four-Colors-xs.jpg","Puzzle"],
["Nova Craft","c:2024/more2/nova-craft/index.html","841"+R+"Nova-Craft-xs.jpg","Puzzle"],
["Basket Hoop","c:2024/construct/311/basket-hoop/index-og.html","843"+R+"Basket-Hoop-xs.jpg","Sports"],
["Head Soccer 2022","o:2023/construct/280/head-soccer-2022/index.html","624"+R+"Head-Soccer-2022-xs.jpg","2 Player"],
["8 Ball Pool Billiard","o:2022/unity3/8-ball-pool-billiard/index.html","442"+R+"8-Ball-Pool-Billiard-xs.jpg","Sports"],
["Basketball io","o:2022/unity3/basketball-io/index.html","302"+R+"Basketball-io-2-xs.jpg","Sports"],
["Basketball King","c:2024/construct/316/basketball-king/index-og.html","907"+R+"basketball-king-xs.jpg","Sports"],
["Football King","o:2024/construct/226/football-king/index.html","739"+R+"Football-King-xs.jpg","Sports"],
["Car Football","o:2023/construct/198/car-football/index.html","405"+R+"Car-Football-xs.jpg","2 Player"],
["Head Soccer Football","o:2022/unity/head-soccer-football/index.html","482"+R+"Head-Soccer-Football-xs.jpg","2 Player"],
["Snake Football","o:2023/construct/200/snake-football/index.html","706"+R+"Snake-Football-xs.jpg","Sports"],
["Basketball Slam Dunk","o:2021/unity2/basketball-slam-dunk/index.html","200"+R+"Basketball-Slam-Dunk-xs.jpg","Sports"],
["Nova Billiard","o:2021/unity2/nova-billiard/index.html","456"+R+"Nova-Billiard-Game-xs.jpg","Sports"],
["Capybara Clicker Pro","o:2023/q2/capybara-clicker-pro/index.html","554"+R+"Capybara-Clicker-Pro-xs.jpg","Sim"],
["Cube Worlds","c:2025/html/cube-worlds/index-og.html","986"+R+"Cube-Worlds-xs.jpg","Sim"],
["Fast Food Manager","c:2025/unity4/fast-food-manager/index-og.html","1114"+R+"fast-food-manager-xs.webp","Sim"],
["Jungle Mart","c:2026/construct/339/jungle-mart/game.html","1247"+R+"jungle-mart-xs.webp","Sim"],
["Nova Clicker","c:2024/construct/314/nova-clicker/index-og.html","981"+R+"Nova-Clicker-xs.jpg","Sim"],
["Cool Brainrot Clicker","c:2025/construct/335/cool-brainrot-clicker/index-og.html","1104"+R+"cool-brainrot-clicker-xs.webp","Sim"],
["Checkout Frenzy","c:2025/unity/checkout-frenzy/index-og.html","974"+R+"checkout-frenzy-cashier-game-xs.jpg","Sim"],
["Fast Food Rush","c:2025/unity/fast-food-rush/index-og.html","979"+R+"fast-food-rush-xs.jpg","Sim"],
["Subway Idle 3D","o:2022/unity4/subway-idle-3d/index.html","586"+R+"Subway-Idle-xs.jpg","Sim"],
["Cat Simulator","o:2022/unity4/cat-simulator/index.html","330"+R+"Cat-Simulator-Online-xs.jpg","Sim"],
["Car Wash","o:2023/unity2/car-wash/index.html","407"+R+"Car-Wash-Online-Game-xs.jpg","Sim"],
["Survival Island","c:2024/unity2/survival-island/index-og.html","970"+R+"Survival-Island-xs.jpg","Sim"],
["Pixelmon Town","c:2025/html/pixelmon-town/game.html","1214"+R+"pixelmon-town-xs.webp","Sim"],
["CubeCraft Survival","c:2025/unity4/cubecraft-survival/index-og.html","1113"+R+"cubecraft-survival-xs.webp","Sim"],
["99 Nights in the Forest","c:2026/unity/99-nights-in-the-forest-survival/game.html","1190"+R+"99-nights-in-the-forest-xs.webp","Sim"],
["Age Of Battle","c:2026/unity/age-of-battle/game.html","1201"+R+"age-of-battle-xs.webp","Strategy"],
["Crown Defense","c:2025/construct/337/crown-defense/index-og.html","1098"+R+"crown-defense-online-xs.webp","Strategy"],
["Kingdom Attack","o:2021/unity3/kingdom-attack/index.html","371"+R+"Kingdom-Attack-xs.jpg","Strategy"],
["Monster Survivors","c:2025/unity/monster-survivors/index-og.html","942"+R+"Monster-survivors-xs.jpg","Action"],
["Kawaii Shooter","c:2024/unity/kawaii-shooter/index-og.html","844"+R+"Kawaii-Shooter-xs.jpg","Action"],
["Zombie War Defense","o:2022/unity/zombie-war-defense/index.html","466"+R+"Zombie-War-Defense-Game-xs.jpg","Action"],
["Dark Ninja Hanjo","o:2023/unity/dark-ninja-hanjo/index.html","451"+R+"Dark-Ninja-Hanjo-xs.jpg","Action"],
["Hero Dragon Power","o:2023/unity/hero-dragon-power/index.html","365"+R+"Hero-Dragon-Power-Game-xs.jpg","Action"],
["Alien Sky Invasion","o:2021/unity3/alien-sky-invasion/index.html","594"+R+"Alien-Sky-Invasion-xs.jpg","Action"],
["Treasure Hunter","o:2022/construct/164/treasure-hunter/index.html","812"+R+"Treasure-Hunter-xs.jpg","Action"],
["Love Tester","o:2021/3/love-tester/index.html","152"+R+"love-tester-xs.jpg","Arcade"],
["Love Tester Story","c:2024/construct/225/love-tester-story/index-og.html","816"+R+"Love-Tester-Story-xs.jpg","Arcade"],
["Romantic Secret Kiss","o:2021/3/romantic-secret-kiss/index.html","483"+R+"Romantic-Secret-Kiss-xs.jpg","Arcade"],
["Julie Beauty Salon","c:2021/1/julie-beauty-salon/index-og.html","1011"+R+"Julie-Beauty-Salon-xs.jpg","Dress Up"],
["Princess Beauty Salon","o:2021/1/princess-beauty-salon/index.html","525"+R+"Princess-Beauty-Salon-xs.jpg","Dress Up"],
["Fun Party Makeup","o:2021/4/fun-party-makeup/index.html","723"+R+"Fun-Party-Makeup-xs.jpg","Dress Up"],
["Wedding Beauty Salon","o:2021/2/wedding-beauty-salon/index.html","421"+R+"Wedding-Beauty-Salon-xs.jpg","Dress Up"],
["Princess Influencer Salon","o:2021/3/princess-influencer-salon/index.html","485"+R+"Princess-Influencer-Salon-xs.jpg","Dress Up"],
["Perfect First Date","o:2021/3/perfect-first-date/index.html","532"+R+"Perfect-First-Date-xs.jpg","Dress Up"],
["Paradise Girls","o:2021/4/paradise-girls/index.html","556"+R+"Pradise-Girls-xs.jpg","Dress Up"],
["Limousine Simulator","o:2021/4/limousine-simulator/index.html","701"+R+"Limousine-Simulator-xs.jpg","Racing"],
["Jeep Driver","c:2021/1/jeep-driver/index-og.html","1039"+R+"jeep-driver-game-3-xs.webp","Racing"],
["Apocalypse Truck","c:2021/1/apocalypse-truck/index-og.html","1015"+R+"apocalypse-truck-xs.jpg","Racing"],
["City Police Cars","c:2021/2/city-police-cars/index-og.html","1053"+R+"city_police_cars_game-4-xs.webp","Racing"],
["Police Chase Drifter","o:2021/3/police-chase-drifter/index.html","155"+R+"Police-Chase-Drifter-Online-xs.jpg","Racing"],
["Police Traffic","o:2021/unity/police-traffic/index.html","187"+R+"Pollice-Traffic-xs.jpg","Racing"],
["Motorbike Traffic","o:2021/unity/motorbike-traffic/index.html","419"+R+"Motorbike-Traffic-Game-xs.jpg","Racing"],
["Drift Rider","o:2023/unity3/drift-rider/index.html","553"+R+"Drift-Rider-xs.jpg","Racing"],
["Burnout Drift Hunter","o:2022/unity4/burnout-drift-hunter/index.html","327"+R+"Burnout-Drift-Hunter-Online-xs.jpg","Racing"],
["Fort Drifter","o:2022/unity3/fort-drifter/index.html","592"+R+"Fort-Drifter-xs.jpg","Racing"],
["Hover Racer Pro","o:2021/unity/hover-racer-pro/index.html","572"+R+"Hover-Racer-Pro-xs.jpg","Racing"],
["Hover Racer","o:2021/unity3/hover-racer/index.html","224"+R+"Hover-Racer-Game-xs.jpg","Racing"],
["2 Player Crazy Racer","o:2022/unity3/2-player-crazy-racer/index.html","617"+R+"2-Player-Crazy-Racer-xs.jpg","2 Player"],
["Mini Cars Racing","c:2021/unity/mini-cars-racing/index-og.html","1010"+R+"Mini-Cars-Racing-xs.jpg","Racing"],
["Crazy Parking Fury","o:2022/unity3/crazy-parking-fury/index.html","643"+R+"Crazy-Parking-Fury-xs.jpg","Racing"],
["Speed Drift Racing","o:2022/construct/124/speed-drift-racing/index.html","801"+R+"Speed-Drift-Racing-xs.jpg","Racing"],
["F1 Drift Racer","o:2022/construct/134/f1-drift-racer/index.html","504"+R+"F1-Drift-Racer-xs.jpg","Racing"],
["Racing Cars","o:2021/1/racing-cars/index.html","661"+R+"Racing-Cars-xs.jpg","Racing"],
["Offroad Rally","o:2023/unity2/offroad-rally/index.html","461"+R+"Offroad-Rally-xs.jpg","Racing"],
["Truck Racing","o:2022/construct/144/truck-racing/index.html","712"+R+"Truck-Racing-xs.jpg","Racing"],
["Tank Racing","o:2022/construct/151/tank-racing/index.html","484"+R+"Tank-Racing-Online-xs.jpg","Racing"],
["Train Racing","o:2022/construct/120/train-racing/index.html","445"+R+"Train-Racing-Game-xs.jpg","Racing"],
["Highway Cars","o:2023/construct/211/highway-cars/index.html","598"+R+"Highway-Cars-xs.jpg","Racing"],
["Survival Karts","c:2024/unity3/survival-karts/index-og.html","887"+R+"survival-karts-play-xs.jpg","Racing"],
["Crazy Moto Racing","c:2022/unity3/crazy-moto-racing/index-og.html","931"+R+"crazy-moto-racing-xs.jpg","Racing"],
["Skateboard Marathon","o:2022/unity3/skateboard-marathon/index.html","518"+R+"Skateboard-Marathon-xs.jpg","Sports"],
["Idle Dev Startup","o:2023/unity3/idle-dev-startup/index.html","566"+R+"Idle-Dev-Startup-Game-xs.jpg","Sim"],
["Stick Guys Defense","o:2022/unity3/stick-guys-defense/index.html","476"+R+"Stick-Guys-Defense-xs.jpg","Strategy"],
["Army Driver","o:2022/construct/63/army-driver/index.html","424"+R+"Army-Driver-xs.jpg","Action"],
["Jacks Village","o:2021/unity/jacks-village/index.html","493"+R+"Jacks-Village-xs.jpg","Action"]
];
// TwoPlayerGames.org games use its /embed/ pages. Row: [title, slug, category, 1 if 2 players]
const TP="https://www.twoplayergames.org/embed/";
const TPG=[
["Basket Random","basket-random","Sports",1],["Soccer Random","soccer-random","Sports",1],["Volley Random","volley-random","Sports",1],["Boxing Random","boxing-random","Sports",1],
["Basketball Stars 2026","basketball-stars-2026","Sports",1],["World Cup Soccer Caps","world-cup-soccer-caps","Sports",1],["Football Legends 2026","football-legends-2026","Sports",1],["Hockey Bros","hockey-bros","Sports",1],
["Tennis Masters 2026","tennis-masters-2026","Sports",1],["Ragdoll Football","ragdoll-football","Sports",1],["Football Bros","football-bros","Sports",1],["Soccer Bros","soccer-bros","Sports",1],
["Baseball Bros","baseball-bros","Sports",1],["Sports Heads Football 2","sports-heads-football-2","Sports",1],["Retro Sports Champion","retro-sports-champion","Sports",1],["Soccer Physics World Cup","soccer-physics-world-cup","Sports",1],
["GoalHeads io","goalheads-io","Sports",1],["Wrestle Bros","wresle-bros","Sports",1],["Mini Putt 4","mini-putt-4","Sports",1],
["MX OffRoad Mountain Bike","mx-offroad-mountain-bike","Racing",1],["MX OffRoad Master","mx-offroad-master","Racing",1],["Night City Racing","night-city-racing","Racing",1],["Grand Extreme Racing","grand-extreme-racing","Racing",1],
["Grand City Racing","grand-city-racing","Racing",1],["Two Punk Racing","two-punk-racing","Racing",1],["Two RX7 Drifters","two-rx7-drifters","Racing",1],["Double Bike Battle","double-bike-battle","Racing",1],
["Summer Rider 3D","summer-rider-3d","Racing",1],["Snow Rush 3D","snow-rush-3d","Racing",1],["Ultimate Flying Car","ultimate-flying-car","Racing",1],["Fly Car Stunt 5","fly-car-stunt-5","Racing",1],
["Grand City Stunts","grand-city-stunts","Racing",1],["Obby on a Bike","obby-on-a-bike","Racing"],["Italian Brainrot Bike Rush","italian-brainrot-bike-rush","Racing"],["Steal Car Duel","steal-car-duel","Racing",1],
["Getaway Shootout","getaway-shootout","Action",1],["House of Hazards","house-of-hazards","Action",1],["Rooftop Snipers","rooftop-snipers","Action",1],["Stickman Kombat 2D","stickman-kombat-2d","Action",1],
["Super Fighters","super-fighters","Action",1],["Super Fighters Ultimate","super-fighters-ultimate","Action",1],["MechaStick Fighter","mechastick-fighter","Action",1],["Gun Mayhem","gun-mayhem","Action",1],
["Gun Mayhem 2 More Mayhem","gun-mayhem-2-more-mayhem","Action",1],["Gun Mayhem Redux","gun-mayhem-redux","Action",1],["Boxhead 2Play","boxhead-2play","Action",1],["Drunken Boxing","drunken-boxing","Action",1],
["Drunken Boxing 2","drunken-boxing-2","Action",1],["Stickman Battle Fighting","stickman-battle-fighting","Action",1],["Stickman Battle 1-4 Players","stickman-battle-1-4-players","Action",1],["Stick Arena: Battle","stick-arena-battle","Action",1],
["Stick War: Infinity Duel","stick-war-infinity-duel","Action",1],["Stick Wars","stick-wars","Action",1],["Tank Trouble","tank-trouble","Action",1],["Dragon Fist 3","dragon-fist-3","Action",1],
["Avatar Fortress Fight 2","avatar-fortress-fight-2","Action",1],["Janissary Battles","janissary-battles","Action",1],["MiniBattles 2-6 Players","minibattles-2-6-players","Action",1],["Tag Run","tag-run","Action",1],
["Paint or Hunt","paint-or-hunt","Action",1],["Flip Duel","flip-duel","Action",1],["Kick Lucky Blocks Online","kick-lucky-blocks-online","Action",1],["Sniper for Brainrots","sniper-for-brainrots","Action"],
["Fire and Water","fire-and-water","Puzzle",1],["Fireboy and Watergirl: Forest Temple","fireboy-and-watergirl-in-the-forest-temple","Puzzle",1],["Fireboy and Watergirl 3: Ice Temple","fireboy-and-watergirl-3-in-the-ice-temple","Puzzle",1],
["Fireboy and Watergirl 4: Crystal Temple","fireboy-and-watergirl-4-the-crystal-temple","Puzzle",1],["Fireboy and Watergirl 5: Elements","fireboy-and-watergirl-5-elements","Puzzle",1],["Fireboy and Watergirl 6: Fairy Tales","fireboy-and-watergirl-6-fairy-tales","Puzzle",1],
["Fireboy and Watergirl 7: Friends","fireboy-and-watergirl-7-and-friends","Puzzle",1],["Hangman","hangman","Puzzle",1],["2048 Duel","2048-duel","Puzzle",1],["Two Player Gold Miner","two-player-gold-miner","Puzzle",1],
["Geometry Vibes","geometry-vibes","Arcade",1],["Geometry Vibes 2 Online","geometry-vibes-2-online","Arcade",1],["Geometry Vibes X-Ball","geometry-vibes-x-ball","Arcade",1],["Geometry Vibes X-Arrow","geometry-vibes-x-arrow","Arcade",1],
["G-Switch 3","g-switch-3","Arcade"],["Fish Eat Fish","fish-eat-fish","Arcade",1],["Fish Eat Getting Big","fish-eat-getting-big","Arcade",1],["Two Ball 3D","two-ball-3d","Arcade",1],
["Pogo Masters","pogo-masters","Arcade",1],["2P Dino Run","2p-dino-run","Arcade",1],["2-3-4 Player Games","2-3-4-player-games","Arcade",1],["Rolling Balls Sea Race","rolling-balls-sea-race","Arcade",1],
["PikWip","pikwip","Arcade",1],["Hook A Brainrot","hook-a-brainrot","Arcade"],["Brainrots Lava Survive Online","brainrots-lava-survive-online","Arcade"],["Lucky Brainrot Blocks Online","lucky-brainrot-blocks-online","Arcade"],
["Tsunami Brainrots Online","tsunami-brainrots-online","Arcade"],["Italian Brainrot Obby Parkour","italian-brainrot-obby-parkour","Arcade"],["Float for Brainrots","float-for-brainrots","Arcade"],["Break a Lucky Egg Brainrots","break-a-lucky-egg-brainrots","Arcade"],
["+1 Speed Keyboard Lucky Escape","1-speed-keyboard-lucky-escape","Arcade"],["Ninja Obby Parkour","ninja-obby-parkour","Arcade"],["Collect Brainrot Arena","collect-brainrot-arena","Arcade"],["Escape the Alien Prison","escape-the-alien-prison","Arcade"],
["Steal Animal Eggs Online","steal-animal-eggs-online","Arcade"],["Janissary Tower","janissary-tower","Strategy",1]
];
